/***** This code was generated by Yaggo. Do not edit ******/

#ifndef __GETSUPERREADINSERTCOUNTSFROMREADPLACEMENTFILETWOPASSES_HPP__
#define __GETSUPERREADINSERTCOUNTSFROMREADPLACEMENTFILETWOPASSES_HPP__

#include <yaggo.hpp>

class getSuperReadInsertCountsFromReadPlacementFileTwoPasses {
public:
  const char *                   output_arg;
  bool                           output_given;
  bool                           fib_flag;
  uint64_t                       number_reads_arg;
  bool                           number_reads_given;
  bool                           debug_flag;
  std::vector<const char *>      input_arg;
  typedef std::vector<const char *>::iterator input_arg_it;
  typedef std::vector<const char *>::const_iterator input_arg_const_it;

  enum {
    USAGE_OPT = 1000
  };

  getSuperReadInsertCountsFromReadPlacementFileTwoPasses() : 
    output_arg(""), output_given(false),
    fib_flag(false),
    number_reads_arg(1000000), number_reads_given(false),
    debug_flag(false)
  { }

  getSuperReadInsertCountsFromReadPlacementFileTwoPasses(int argc, char* argv[]) :
    output_arg(""), output_given(false),
    fib_flag(false),
    number_reads_arg(1000000), number_reads_given(false),
    debug_flag(false)
  { parse(argc, argv); }

  void parse(int argc, char* argv[]) {
    static struct option long_options[] = {
      {"output", 1, 0, 'o'},
      {"fib", 0, 0, 'f'},
      {"number-reads", 1, 0, 'n'},
      {"debug", 0, 0, 'd'},
      {"help", 0, 0, 'h'},
      {"usage", 0, 0, USAGE_OPT},
      {"version", 0, 0, 'V'},
      {0, 0, 0, 0}
    };
    static const char *short_options = "hVo:fn:d";

    std::string err;
#define CHECK_ERR(type,val,which) if(!err.empty()) { std::cerr << "Invalid " #type " '" << val << "' for [" which "]: " << err << "\n"; exit(1); }
    while(true) { 
      int index = -1;
      int c = getopt_long(argc, argv, short_options, long_options, &index);
      if(c == -1) break;
      switch(c) {
      case ':': 
        std::cerr << "Missing required argument for "
                  << (index == -1 ? std::string(1, (char)optopt) : std::string(long_options[index].name))
                  << std::endl;
        exit(1);
      case 'h':
        std::cout << usage() << "\n\n" << help() << std::endl;
        exit(0);
      case USAGE_OPT:
        std::cout << usage() << "\nUse --help for more information." << std::endl;
        exit(0);
      case 'V':
        print_version();
        exit(0);
      case '?':
        std::cerr << "Use --usage or --help for some help\n";
        exit(1);
      case 'o':
        output_given = true;
        output_arg = optarg;
        break;
      case 'f':
        fib_flag = true;
        break;
      case 'n':
        number_reads_given = true;
        number_reads_arg = yaggo::conv_uint<uint64_t>((const char *)optarg, err, true);
        CHECK_ERR(uint64_t, optarg, "-n, --number-reads=uint64")
        break;
      case 'd':
        debug_flag = true;
        break;
      }
    }
    if(argc - optind < 0)
      error("Requires at least 0 argument.");
    for( ; optind < argc; ++optind) {
      input_arg.push_back(argv[optind]);
    }
  }
#define getSuperReadInsertCountsFromReadPlacementFileTwoPasses_USAGE "Usage: getSuperReadInsertCountsFromReadPlacementFileTwoPasses [options] input:path+"
  const char * usage() const { return getSuperReadInsertCountsFromReadPlacementFileTwoPasses_USAGE; }
  void error(const char *msg) { 
    std::cerr << "Error: " << msg << "\n" << usage()
              << "\nUse --help for more information"
              << std::endl;
    exit(1);
  }
#define getSuperReadInsertCountsFromReadPlacementFileTwoPasses_HELP "Count number of occurences of each super-read\n\nNo long description!\n\n" \
  "Options (default value in (), *required):\n" \
  " -o, --output=path                        Output file\n" \
  " -f, --fib                                Use fibonacci encoding (false)\n" \
  " -n, --number-reads=uint64                Estimated number of super-reads (1000000)\n" \
  " -d, --debug                              Output debugging information (false)\n" \
  "     --usage                              Usage\n" \
  " -h, --help                               This message\n" \
  " -V, --version                            Version"

  const char * help() const { return getSuperReadInsertCountsFromReadPlacementFileTwoPasses_HELP; }
#define getSuperReadInsertCountsFromReadPlacementFileTwoPasses_HIDDEN "Hidden options:"

  const char * hidden() const { return getSuperReadInsertCountsFromReadPlacementFileTwoPasses_HIDDEN; }
  void print_version(std::ostream &os = std::cout) const {
#ifndef PACKAGE_VERSION
#define PACKAGE_VERSION "0.0.0"
#endif
    os << PACKAGE_VERSION << "\n";
  }
  void dump(std::ostream &os = std::cout) {
    os << "output_given:" << output_given << " output_arg:" << output_arg << "\n";
    os << "fib_flag:" << fib_flag << "\n";
    os << "number_reads_given:" << number_reads_given << " number_reads_arg:" << number_reads_arg << "\n";
    os << "debug_flag:" << debug_flag << "\n";
    os << "input_arg:" << yaggo::vec_str(input_arg) << "\n";
  }
private:
};

#endif // __GETSUPERREADINSERTCOUNTSFROMREADPLACEMENTFILETWOPASSES_HPP__"
