/***** This code was generated by Yaggo. Do not edit ******/

#ifndef __TEST_MAIN_HPP__
#define __TEST_MAIN_HPP__

#include <yaggo.hpp>

class test_main {
public:
  uint32_t                       seed_arg;
  bool                           seed_given;

  enum {
    USAGE_OPT = 1000
  };

  test_main(int argc, char *argv[]) :
    seed_arg(), seed_given(false)
  {
    static struct option long_options[] = {
      {"seed", 1, 0, 's'},
      {"help", 0, 0, 'h'},
      {"usage", 0, 0, USAGE_OPT},
      {"version", 0, 0, 'V'},
      {0, 0, 0, 0}
    };
    static const char *short_options = "hVs:";

    std::string err;
#define CHECK_ERR(type,val,which) if(!err.empty()) { std::cerr << "Invalid " #type " '" << val << "' for [" which "]: " << err << "\n"; exit(1); }
    while(true) { 
      int index = -1;
      int c = getopt_long(argc, argv, short_options, long_options, &index);
      if(c == -1) break;
      switch(c) {
      case ':': 
        std::cerr << "Missing required argument for "
                  << (index == -1 ? std::string(1, (char)optopt) : std::string(long_options[index].name))
                  << std::endl;
        exit(1);
      case 'h':
        std::cout << usage() << "\n\n" << help() << std::endl;
        exit(0);
      case USAGE_OPT:
        std::cout << usage() << "\nUse --help for more information." << std::endl;
        exit(0);
      case 'V':
        print_version();
        exit(0);
      case '?':
        std::cerr << "Use --usage or --help for some help\n";
        exit(1);
      case 's':
        seed_given = true;
        seed_arg = yaggo::conv_uint<uint32_t>((const char *)optarg, err, false);
        CHECK_ERR(uint32_t, optarg, "-s, --seed=uint32")
        break;
      }
    }
    if(argc - optind != 0)
      error("Requires exactly 0 argument.");
  }
#define test_main_USAGE "Usage: test_main [options]"
  const char * usage() const { return test_main_USAGE; }
  void error(const char *msg) { 
    std::cerr << "Error: " << msg << "\n" << usage()
              << "\nUse --help for more information"
              << std::endl;
    exit(1);
  }
#define test_main_HELP "Unit tests\n\n" \
  "Options (default value in (), *required):\n" \
  " -s, --seed=uint32                        Random seed\n" \
  "     --usage                              Usage\n" \
  " -h, --help                               This message\n" \
  " -V, --version                            Version"

  const char * help() const { return test_main_HELP; }
#define test_main_HIDDEN "Hidden options:"

  const char * hidden() const { return test_main_HIDDEN; }
  void print_version(std::ostream &os = std::cout) const {
#ifndef PACKAGE_VERSION
#define PACKAGE_VERSION "0.0.0"
#endif
    os << PACKAGE_VERSION << "\n";
  }
  void dump(std::ostream &os = std::cout) {
    os << "seed_given:" << seed_given << " seed_arg:" << seed_arg << "\n";
  }
private:
};

#endif // __TEST_MAIN_HPP__"
