/*
  File autogenerated by gengetopt version 2.22.4
  generated with the following command:
  gengetopt --unamed-opts=database.jf --show-required --default-optional -c cpp -H hpp -F create_k_unitigs_cmdline -f create_k_unitigs_cmd_parser -a create_k_unitigs_args_info

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "create_k_unitigs_cmdline.hpp"

const char *create_k_unitigs_args_info_purpose = "Create k-unitigs (unipaths) from a Jellyfish k-mer database.";

const char *create_k_unitigs_args_info_usage = "Usage: create_k_unitigs [OPTIONS]... [database.jf]...";

const char *create_k_unitigs_args_info_description = "";

const char *create_k_unitigs_args_info_help[] = {
  "  -h, --help             Print help and exit",
  "  -V, --version          Print version and exit",
  "  -C, --both-strands     Both strands  (default=off)",
  "  -t, --threads=INT      Number of threads  (default=`1')",
  "  -v, --verbose          Be verbose  (default=off)",
  "  -o, --prefix=STRING    Output prefix  (default=`k_unitigs')",
  "  -l, --min-len=k+1      Minimum length of k-unitig to output",
  "  -m, --min-cov=INT      Minimum k-mer coverage to be considered  (default=`2')",
  "  -M, --min-cont=INT     Minimum k-mer coverage to continue  (default=`3')",
  "      --cont-on-low      Continue on unique low k-mer (count < m)  \n                           (default=off)",
  "      --low-stretch=INT  Max number of low k-mer  (default=`3')",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
} create_k_unitigs_cmd_parser_arg_type;

static
void clear_given (struct create_k_unitigs_args_info *args_info);
static
void clear_args (struct create_k_unitigs_args_info *args_info);

static int
create_k_unitigs_cmd_parser_internal (int argc, char **argv, struct create_k_unitigs_args_info *args_info,
                        struct create_k_unitigs_cmd_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct create_k_unitigs_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->both_strands_given = 0 ;
  args_info->threads_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->prefix_given = 0 ;
  args_info->min_len_given = 0 ;
  args_info->min_cov_given = 0 ;
  args_info->min_cont_given = 0 ;
  args_info->cont_on_low_given = 0 ;
  args_info->low_stretch_given = 0 ;
}

static
void clear_args (struct create_k_unitigs_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->both_strands_flag = 0;
  args_info->threads_arg = 1;
  args_info->threads_orig = NULL;
  args_info->verbose_flag = 0;
  args_info->prefix_arg = gengetopt_strdup ("k_unitigs");
  args_info->prefix_orig = NULL;
  args_info->min_len_orig = NULL;
  args_info->min_cov_arg = 2;
  args_info->min_cov_orig = NULL;
  args_info->min_cont_arg = 3;
  args_info->min_cont_orig = NULL;
  args_info->cont_on_low_flag = 0;
  args_info->low_stretch_arg = 3;
  args_info->low_stretch_orig = NULL;
  
}

static
void init_args_info(struct create_k_unitigs_args_info *args_info)
{


  args_info->help_help = create_k_unitigs_args_info_help[0] ;
  args_info->version_help = create_k_unitigs_args_info_help[1] ;
  args_info->both_strands_help = create_k_unitigs_args_info_help[2] ;
  args_info->threads_help = create_k_unitigs_args_info_help[3] ;
  args_info->verbose_help = create_k_unitigs_args_info_help[4] ;
  args_info->prefix_help = create_k_unitigs_args_info_help[5] ;
  args_info->min_len_help = create_k_unitigs_args_info_help[6] ;
  args_info->min_cov_help = create_k_unitigs_args_info_help[7] ;
  args_info->min_cont_help = create_k_unitigs_args_info_help[8] ;
  args_info->cont_on_low_help = create_k_unitigs_args_info_help[9] ;
  args_info->low_stretch_help = create_k_unitigs_args_info_help[10] ;
  
}

void
create_k_unitigs_cmd_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CREATE_K_UNITIGS_CMD_PARSER_PACKAGE_NAME) ? CREATE_K_UNITIGS_CMD_PARSER_PACKAGE_NAME : CREATE_K_UNITIGS_CMD_PARSER_PACKAGE),
     CREATE_K_UNITIGS_CMD_PARSER_VERSION);
}

static void print_help_common(void) {
  create_k_unitigs_cmd_parser_print_version ();

  if (strlen(create_k_unitigs_args_info_purpose) > 0)
    printf("\n%s\n", create_k_unitigs_args_info_purpose);

  if (strlen(create_k_unitigs_args_info_usage) > 0)
    printf("\n%s\n", create_k_unitigs_args_info_usage);

  printf("\n");

  if (strlen(create_k_unitigs_args_info_description) > 0)
    printf("%s\n\n", create_k_unitigs_args_info_description);
}

void
create_k_unitigs_cmd_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (create_k_unitigs_args_info_help[i])
    printf("%s\n", create_k_unitigs_args_info_help[i++]);
}

void
create_k_unitigs_cmd_parser_init (struct create_k_unitigs_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
create_k_unitigs_cmd_parser_params_init(struct create_k_unitigs_cmd_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct create_k_unitigs_cmd_parser_params *
create_k_unitigs_cmd_parser_params_create(void)
{
  struct create_k_unitigs_cmd_parser_params *params = 
    (struct create_k_unitigs_cmd_parser_params *)malloc(sizeof(struct create_k_unitigs_cmd_parser_params));
  create_k_unitigs_cmd_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
create_k_unitigs_cmd_parser_release (struct create_k_unitigs_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->threads_orig));
  free_string_field (&(args_info->prefix_arg));
  free_string_field (&(args_info->prefix_orig));
  free_string_field (&(args_info->min_len_orig));
  free_string_field (&(args_info->min_cov_orig));
  free_string_field (&(args_info->min_cont_orig));
  free_string_field (&(args_info->low_stretch_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
create_k_unitigs_cmd_parser_dump(FILE *outfile, struct create_k_unitigs_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CREATE_K_UNITIGS_CMD_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->both_strands_given)
    write_into_file(outfile, "both-strands", 0, 0 );
  if (args_info->threads_given)
    write_into_file(outfile, "threads", args_info->threads_orig, 0);
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", 0, 0 );
  if (args_info->prefix_given)
    write_into_file(outfile, "prefix", args_info->prefix_orig, 0);
  if (args_info->min_len_given)
    write_into_file(outfile, "min-len", args_info->min_len_orig, 0);
  if (args_info->min_cov_given)
    write_into_file(outfile, "min-cov", args_info->min_cov_orig, 0);
  if (args_info->min_cont_given)
    write_into_file(outfile, "min-cont", args_info->min_cont_orig, 0);
  if (args_info->cont_on_low_given)
    write_into_file(outfile, "cont-on-low", 0, 0 );
  if (args_info->low_stretch_given)
    write_into_file(outfile, "low-stretch", args_info->low_stretch_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
create_k_unitigs_cmd_parser_file_save(const char *filename, struct create_k_unitigs_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CREATE_K_UNITIGS_CMD_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = create_k_unitigs_cmd_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
create_k_unitigs_cmd_parser_free (struct create_k_unitigs_args_info *args_info)
{
  create_k_unitigs_cmd_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
create_k_unitigs_cmd_parser (int argc, char **argv, struct create_k_unitigs_args_info *args_info)
{
  return create_k_unitigs_cmd_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
create_k_unitigs_cmd_parser_ext (int argc, char **argv, struct create_k_unitigs_args_info *args_info,
                   struct create_k_unitigs_cmd_parser_params *params)
{
  int result;
  result = create_k_unitigs_cmd_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      create_k_unitigs_cmd_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
create_k_unitigs_cmd_parser2 (int argc, char **argv, struct create_k_unitigs_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct create_k_unitigs_cmd_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = create_k_unitigs_cmd_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      create_k_unitigs_cmd_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
create_k_unitigs_cmd_parser_required (struct create_k_unitigs_args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see create_k_unitigs_cmd_parser_params.check_ambiguity
 * @param override @see create_k_unitigs_cmd_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               create_k_unitigs_cmd_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
create_k_unitigs_cmd_parser_internal (
  int argc, char **argv, struct create_k_unitigs_args_info *args_info,
                        struct create_k_unitigs_cmd_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct create_k_unitigs_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    create_k_unitigs_cmd_parser_init (args_info);

  create_k_unitigs_cmd_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "both-strands",	0, NULL, 'C' },
        { "threads",	1, NULL, 't' },
        { "verbose",	0, NULL, 'v' },
        { "prefix",	1, NULL, 'o' },
        { "min-len",	1, NULL, 'l' },
        { "min-cov",	1, NULL, 'm' },
        { "min-cont",	1, NULL, 'M' },
        { "cont-on-low",	0, NULL, 0 },
        { "low-stretch",	1, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVCt:vo:l:m:M:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          create_k_unitigs_cmd_parser_print_help ();
          create_k_unitigs_cmd_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          create_k_unitigs_cmd_parser_print_version ();
          create_k_unitigs_cmd_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'C':	/* Both strands.  */
        
        
          if (update_arg((void *)&(args_info->both_strands_flag), 0, &(args_info->both_strands_given),
              &(local_args_info.both_strands_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "both-strands", 'C',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Number of threads.  */
        
        
          if (update_arg( (void *)&(args_info->threads_arg), 
               &(args_info->threads_orig), &(args_info->threads_given),
              &(local_args_info.threads_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "threads", 't',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* Be verbose.  */
        
        
          if (update_arg((void *)&(args_info->verbose_flag), 0, &(args_info->verbose_given),
              &(local_args_info.verbose_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "verbose", 'v',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Output prefix.  */
        
        
          if (update_arg( (void *)&(args_info->prefix_arg), 
               &(args_info->prefix_orig), &(args_info->prefix_given),
              &(local_args_info.prefix_given), optarg, 0, "k_unitigs", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "prefix", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* Minimum length of k-unitig to output.  */
        
        
          if (update_arg( (void *)&(args_info->min_len_arg), 
               &(args_info->min_len_orig), &(args_info->min_len_given),
              &(local_args_info.min_len_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "min-len", 'l',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Minimum k-mer coverage to be considered.  */
        
        
          if (update_arg( (void *)&(args_info->min_cov_arg), 
               &(args_info->min_cov_orig), &(args_info->min_cov_given),
              &(local_args_info.min_cov_given), optarg, 0, "2", ARG_INT,
              check_ambiguity, override, 0, 0,
              "min-cov", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'M':	/* Minimum k-mer coverage to continue.  */
        
        
          if (update_arg( (void *)&(args_info->min_cont_arg), 
               &(args_info->min_cont_orig), &(args_info->min_cont_given),
              &(local_args_info.min_cont_given), optarg, 0, "3", ARG_INT,
              check_ambiguity, override, 0, 0,
              "min-cont", 'M',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Continue on unique low k-mer (count < m).  */
          if (strcmp (long_options[option_index].name, "cont-on-low") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->cont_on_low_flag), 0, &(args_info->cont_on_low_given),
                &(local_args_info.cont_on_low_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "cont-on-low", '-',
                additional_error))
              goto failure;
          
          }
          /* Max number of low k-mer.  */
          else if (strcmp (long_options[option_index].name, "low-stretch") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->low_stretch_arg), 
                 &(args_info->low_stretch_orig), &(args_info->low_stretch_given),
                &(local_args_info.low_stretch_given), optarg, 0, "3", ARG_INT,
                check_ambiguity, override, 0, 0,
                "low-stretch", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CREATE_K_UNITIGS_CMD_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  create_k_unitigs_cmd_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  create_k_unitigs_cmd_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
