/***** This code was generated by Yaggo. Do not edit ******/

#ifndef __REDUCE_SR_HPP__
#define __REDUCE_SR_HPP__

#include <yaggo.hpp>

class reduce_sr {
public:
  int                            maximum_search_depth_arg;
  bool                           maximum_search_depth_given;
  uint64_t                       largestkunitig_arg;

  enum {
    USAGE_OPT = 1000
  };

  reduce_sr(int argc, char *argv[]) :
    maximum_search_depth_arg(100), maximum_search_depth_given(false)
  {
    static struct option long_options[] = {
      {"maximum-search-depth", 1, 0, 'd'},
      {"help", 0, 0, 'h'},
      {"usage", 0, 0, USAGE_OPT},
      {"version", 0, 0, 'V'},
      {0, 0, 0, 0}
    };
    static const char *short_options = "hVd:";

    std::string err;
#define CHECK_ERR(type,val,which) if(!err.empty()) { std::cerr << "Invalid " #type " '" << val << "' for [" which "]: " << err << "\n"; exit(1); }
    while(true) { 
      int index = -1;
      int c = getopt_long(argc, argv, short_options, long_options, &index);
      if(c == -1) break;
      switch(c) {
      case ':': 
        std::cerr << "Missing required argument for "
                  << (index == -1 ? std::string(1, (char)optopt) : std::string(long_options[index].name))
                  << std::endl;
        exit(1);
      case 'h':
        std::cout << usage() << "\n\n" << help() << std::endl;
        exit(0);
      case USAGE_OPT:
        std::cout << usage() << "\nUse --help for more information." << std::endl;
        exit(0);
      case 'V':
        print_version();
        exit(0);
      case '?':
        std::cerr << "Use --usage or --help for some help\n";
        exit(1);
      case 'd':
        maximum_search_depth_given = true;
        maximum_search_depth_arg = yaggo::conv_int<int>((const char *)optarg, err, false);
        CHECK_ERR(int_t, optarg, "-d, --maximum-search-depth=int")
        break;
      }
    }
    if(argc - optind != 1)
      error("Requires exactly 1 argument.");
    largestkunitig_arg = yaggo::conv_uint<uint64_t>((const char *)argv[optind], err, false);
    CHECK_ERR(uint64_t, argv[optind], "largestkunitig")
    ++optind;
  }
#define reduce_sr_USAGE "Usage: reduce_sr [options] largestkunitig:uint64"
  const char * usage() const { return reduce_sr_USAGE; }
  void error(const char *msg) { 
    std::cerr << "Error: " << msg << "\n" << usage()
              << "\nUse --help for more information"
              << std::endl;
    exit(1);
  }
#define reduce_sr_HELP "Reduce contained SuperReads to their largest container.\n\nLong description\n\n" \
  "Options (default value in (), *required):\n" \
  " -d, --maximum-search-depth=int           Check at most this many possible containing SuperReads (100)\n" \
  "     --usage                              Usage\n" \
  " -h, --help                               This message\n" \
  " -V, --version                            Version"

  const char * help() const { return reduce_sr_HELP; }
#define reduce_sr_HIDDEN "Hidden options:"

  const char * hidden() const { return reduce_sr_HIDDEN; }
  void print_version(std::ostream &os = std::cout) const {
#ifndef PACKAGE_VERSION
#define PACKAGE_VERSION "0.0.0"
#endif
    os << PACKAGE_VERSION << "\n";
  }
  void dump(std::ostream &os = std::cout) {
    os << "maximum_search_depth_given:" << maximum_search_depth_given << " maximum_search_depth_arg:" << maximum_search_depth_arg << "\n";
    os << "largestkunitig_arg:" << largestkunitig_arg << "\n";
  }
private:
};

#endif // __REDUCE_SR_HPP__"
