/***** This code was generated by Yaggo. Do not edit ******/

#ifndef __SORTED_MERGE_HPP__
#define __SORTED_MERGE_HPP__

#include <yaggo.hpp>

class sorted_merge {
public:
  uint32_t                       key_arg;
  bool                           key_given;
  const char *                   output_arg;
  bool                           output_given;
  bool                           numerical_flag;
  std::vector<const char *>      input_arg;
  typedef std::vector<const char *>::iterator input_arg_it;
  typedef std::vector<const char *>::const_iterator input_arg_const_it;

  enum {
    USAGE_OPT = 1000
  };

  sorted_merge(int argc, char *argv[]) :
    key_arg(1), key_given(false),
    output_arg("/dev/fd/1"), output_given(false),
    numerical_flag(false)
  {
    static struct option long_options[] = {
      {"key", 1, 0, 'k'},
      {"output", 1, 0, 'o'},
      {"numerical", 0, 0, 'n'},
      {"help", 0, 0, 'h'},
      {"usage", 0, 0, USAGE_OPT},
      {"version", 0, 0, 'V'},
      {0, 0, 0, 0}
    };
    static const char *short_options = "hVk:o:n";

    std::string err;
#define CHECK_ERR(type,val,which) if(!err.empty()) { std::cerr << "Invalid " #type " '" << val << "' for [" which "]: " << err << "\n"; exit(1); }
    while(true) { 
      int index = -1;
      int c = getopt_long(argc, argv, short_options, long_options, &index);
      if(c == -1) break;
      switch(c) {
      case ':': 
        std::cerr << "Missing required argument for "
                  << (index == -1 ? std::string(1, (char)optopt) : std::string(long_options[index].name))
                  << std::endl;
        exit(1);
      case 'h':
        std::cout << usage() << "\n\n" << help() << std::endl;
        exit(0);
      case USAGE_OPT:
        std::cout << usage() << "\nUse --help for more information." << std::endl;
        exit(0);
      case 'V':
        print_version();
        exit(0);
      case '?':
        std::cerr << "Use --usage or --help for some help\n";
        exit(1);
      case 'k':
        key_given = true;
        key_arg = yaggo::conv_uint<uint32_t>((const char *)optarg, err, false);
        CHECK_ERR(uint32_t, optarg, "-k, --key=uint32")
        break;
      case 'o':
        output_given = true;
        output_arg = optarg;
        break;
      case 'n':
        numerical_flag = true;
        break;
      }
    }
    if(argc - optind < 2)
      error("Requires at least 2 arguments.");
    for( ; optind < argc; ++optind) {
      input_arg.push_back(argv[optind]);
    }
  }
#define sorted_merge_USAGE "Usage: sorted_merge [options] input:path+"
  const char * usage() const { return sorted_merge_USAGE; }
  void error(const char *msg) { 
    std::cerr << "Error: " << msg << "\n" << usage()
              << "\nUse --help for more information"
              << std::endl;
    exit(1);
  }
#define sorted_merge_HELP "Merge sorted files, similar to sort -m.\n\n" \
  "Options (default value in (), *required):\n" \
  " -k, --key=uint32                         Key (1 base column number) for sorting (1)\n" \
  " -o, --output=path                        Output file instead of stdout (/dev/fd/1)\n" \
  " -n, --numerical                          Numerical sort (false)\n" \
  "     --usage                              Usage\n" \
  " -h, --help                               This message\n" \
  " -V, --version                            Version"

  const char * help() const { return sorted_merge_HELP; }
#define sorted_merge_HIDDEN "Hidden options:"

  const char * hidden() const { return sorted_merge_HIDDEN; }
  void print_version(std::ostream &os = std::cout) const {
#ifndef PACKAGE_VERSION
#define PACKAGE_VERSION "0.0.0"
#endif
    os << PACKAGE_VERSION << "\n";
  }
  void dump(std::ostream &os = std::cout) {
    os << "key_given:" << key_given << " key_arg:" << key_arg << "\n";
    os << "output_given:" << output_given << " output_arg:" << output_arg << "\n";
    os << "numerical_flag:" << numerical_flag << "\n";
    os << "input_arg:" << yaggo::vec_str(input_arg) << "\n";
  }
private:
};

#endif // __SORTED_MERGE_HPP__"
